"""Database models."""

from .access_log import AccessLog
from .application import Application
from .audit_log import (
    ACTION_BADGES,
    ACTION_CREATE_SIMULATION,
    ACTION_CREATE_USER,
    ACTION_DELETE_DATA,
    ACTION_DELETE_SIMULATION,
    ACTION_DELETE_USER,
    ACTION_LABELS,
    ACTION_LOGIN,
    ACTION_LOGOUT,
    ACTION_RUN_SIMULATION,
    ACTION_UPDATE_USER,
    ACTION_UPLOAD_DATA,
    AuditLog,
)
from .material import (
    DATA_SOURCE_STANDARD,
    DATA_SOURCE_SUBSEATEC,
    DATA_SOURCES,
    DIAGRAM_TYPE_CCT,
    DIAGRAM_TYPE_TTT,
    DIAGRAM_TYPES,
    PHASE_AUSTENITE,
    PHASE_BAINITE,
    PHASE_CEMENTITE,
    PHASE_FERRITE,
    PHASE_LABELS,
    PHASE_MARTENSITE,
    PHASE_PEARLITE,
    PHASES,
    PROPERTY_TYPE_CONSTANT,
    PROPERTY_TYPE_CURVE,
    PROPERTY_TYPE_EQUATION,
    PROPERTY_TYPE_POLYNOMIAL,
    PROPERTY_TYPE_TABLE,
    PROPERTY_TYPES,
    MaterialProperty,
    PhaseDiagram,
    PhaseProperty,
    SteelComposition,
    SteelGrade,
)
from .material_changelog import MaterialChangeLog
from .measured_data import MeasuredData
from .permission import UserPermission
from .session import UserSession
from .simulation import (
    DEFAULT_HTC,
    GEOMETRY_CYLINDER,
    GEOMETRY_PLATE,
    GEOMETRY_RING,
    GEOMETRY_TYPES,
    PROCESS_LABELS,
    PROCESS_TYPES,
    STATUS_COMPLETED,
    STATUS_DRAFT,
    STATUS_FAILED,
    STATUS_QUEUED,
    STATUS_READY,
    STATUS_RUNNING,
    STATUSES,
    HeatTreatmentTemplate,
    Simulation,
    SimulationResult,
)
from .snapshot import SimulationSnapshot
from .system_setting import SystemSetting
from .ttt_parameters import (
    B_MODEL_ARRHENIUS,
    B_MODEL_GAUSSIAN,
    B_MODEL_POLYNOMIAL,
    B_MODEL_TYPES,
    CURVE_POS_FIFTY,
    CURVE_POS_FINISH,
    CURVE_POS_START,
    CURVE_POSITIONS,
    CURVE_TYPE_CCT,
    CURVE_TYPE_TTT,
    CURVE_TYPES,
    TTT_SOURCE_CALIBRATED,
    TTT_SOURCE_EMPIRICAL,
    TTT_SOURCE_LITERATURE,
    TTT_SOURCES,
    JMAKParameters,
    MartensiteParameters,
    TTTCalibrationData,
    TTTCurve,
    TTTParameters,
)
from .user import ROLE_ADMIN, ROLE_ENGINEER, ROLE_LABELS, ROLES, User, admin_required
from .weld_project import (
    PROJECT_STATUSES,
    RESULT_COOLING_RATE,
    RESULT_LINE_PROFILE,
    RESULT_TEMPERATURE_FIELD,
    RESULT_THERMAL_CYCLE,
    RESULT_TYPES,
    STRING_COMPLETED,
    STRING_FAILED,
    STRING_PENDING,
    STRING_RUNNING,
    STRING_STATUSES,
    TEMP_MODE_CALCULATED,
    TEMP_MODE_MANUAL,
    TEMP_MODE_SOLIDIFICATION,
    TEMP_MODES,
    WELD_PROCESS_LABELS,
    WELD_PROCESS_TYPES,
    WeldProject,
    WeldResult,
    WeldString,
)

__all__ = [
    # User models
    "User",
    "ROLE_ENGINEER",
    "ROLE_ADMIN",
    "ROLES",
    "ROLE_LABELS",
    "admin_required",
    # Material models (PostgreSQL)
    "SteelGrade",
    "MaterialProperty",
    "PhaseDiagram",
    "PhaseProperty",
    "SteelComposition",
    "PROPERTY_TYPE_CONSTANT",
    "PROPERTY_TYPE_CURVE",
    "PROPERTY_TYPE_TABLE",
    "PROPERTY_TYPE_POLYNOMIAL",
    "PROPERTY_TYPE_EQUATION",
    "PROPERTY_TYPES",
    "DATA_SOURCE_STANDARD",
    "DATA_SOURCE_SUBSEATEC",
    "DATA_SOURCES",
    "DIAGRAM_TYPE_CCT",
    "DIAGRAM_TYPE_TTT",
    "DIAGRAM_TYPES",
    "PHASE_FERRITE",
    "PHASE_AUSTENITE",
    "PHASE_MARTENSITE",
    "PHASE_BAINITE",
    "PHASE_PEARLITE",
    "PHASE_CEMENTITE",
    "PHASES",
    "PHASE_LABELS",
    # Simulation models (PostgreSQL)
    "Simulation",
    "SimulationResult",
    "HeatTreatmentTemplate",
    "STATUS_DRAFT",
    "STATUS_READY",
    "STATUS_QUEUED",
    "STATUS_RUNNING",
    "STATUS_COMPLETED",
    "STATUS_FAILED",
    "STATUSES",
    "GEOMETRY_CYLINDER",
    "GEOMETRY_PLATE",
    "GEOMETRY_RING",
    "GEOMETRY_TYPES",
    "PROCESS_TYPES",
    "PROCESS_LABELS",
    "DEFAULT_HTC",
    # Weld project models (PostgreSQL - Phase 4)
    "WeldProject",
    "WeldString",
    "WeldResult",
    "PROJECT_STATUSES",
    "WELD_PROCESS_TYPES",
    "WELD_PROCESS_LABELS",
    "STRING_STATUSES",
    "STRING_PENDING",
    "STRING_RUNNING",
    "STRING_COMPLETED",
    "STRING_FAILED",
    "TEMP_MODES",
    "TEMP_MODE_CALCULATED",
    "TEMP_MODE_MANUAL",
    "TEMP_MODE_SOLIDIFICATION",
    "RESULT_TYPES",
    "RESULT_THERMAL_CYCLE",
    "RESULT_TEMPERATURE_FIELD",
    "RESULT_COOLING_RATE",
    "RESULT_LINE_PROFILE",
    # Measured data models
    "MeasuredData",
    # Snapshot versioning
    "SimulationSnapshot",
    # TTT/CCT parameters (PostgreSQL)
    "TTTParameters",
    "JMAKParameters",
    "MartensiteParameters",
    "TTTCalibrationData",
    "TTTCurve",
    "TTT_SOURCE_LITERATURE",
    "TTT_SOURCE_CALIBRATED",
    "TTT_SOURCE_EMPIRICAL",
    "TTT_SOURCES",
    "B_MODEL_GAUSSIAN",
    "B_MODEL_ARRHENIUS",
    "B_MODEL_POLYNOMIAL",
    "B_MODEL_TYPES",
    "CURVE_TYPE_TTT",
    "CURVE_TYPE_CCT",
    "CURVE_TYPES",
    "CURVE_POS_START",
    "CURVE_POS_FIFTY",
    "CURVE_POS_FINISH",
    "CURVE_POSITIONS",
    # Material change log
    "MaterialChangeLog",
    # System settings
    "SystemSetting",
    # Portal models
    "Application",
    "UserPermission",
    "UserSession",
    "AccessLog",
    # Audit log
    "AuditLog",
    "ACTION_LOGIN",
    "ACTION_LOGOUT",
    "ACTION_CREATE_USER",
    "ACTION_DELETE_USER",
    "ACTION_UPDATE_USER",
    "ACTION_RUN_SIMULATION",
    "ACTION_DELETE_SIMULATION",
    "ACTION_CREATE_SIMULATION",
    "ACTION_UPLOAD_DATA",
    "ACTION_DELETE_DATA",
    "ACTION_LABELS",
    "ACTION_BADGES",
]
