"""Database models."""
from .user import (
    User,
    ROLE_ENGINEER, ROLE_ADMIN,
    ROLES, ROLE_LABELS,
    admin_required
)
from .material import (
    SteelGrade,
    MaterialProperty,
    PhaseDiagram,
    PROPERTY_TYPE_CONSTANT, PROPERTY_TYPE_CURVE, PROPERTY_TYPE_TABLE,
    PROPERTY_TYPE_POLYNOMIAL, PROPERTY_TYPE_EQUATION, PROPERTY_TYPES,
    DATA_SOURCE_STANDARD, DATA_SOURCE_SUBSEATEC, DATA_SOURCES,
    DIAGRAM_TYPE_CCT, DIAGRAM_TYPE_TTT, DIAGRAM_TYPES,
)
from .simulation import (
    Simulation,
    SimulationResult,
    STATUS_DRAFT, STATUS_READY, STATUS_RUNNING, STATUS_COMPLETED, STATUS_FAILED, STATUSES,
    GEOMETRY_CYLINDER, GEOMETRY_PLATE, GEOMETRY_RING, GEOMETRY_TYPES,
    PROCESS_TYPES, PROCESS_LABELS, DEFAULT_HTC,
)

__all__ = [
    # User models
    'User',
    'ROLE_ENGINEER', 'ROLE_ADMIN',
    'ROLES', 'ROLE_LABELS',
    'admin_required',
    # Material models (PostgreSQL)
    'SteelGrade',
    'MaterialProperty',
    'PhaseDiagram',
    'PROPERTY_TYPE_CONSTANT', 'PROPERTY_TYPE_CURVE', 'PROPERTY_TYPE_TABLE',
    'PROPERTY_TYPE_POLYNOMIAL', 'PROPERTY_TYPE_EQUATION', 'PROPERTY_TYPES',
    'DATA_SOURCE_STANDARD', 'DATA_SOURCE_SUBSEATEC', 'DATA_SOURCES',
    'DIAGRAM_TYPE_CCT', 'DIAGRAM_TYPE_TTT', 'DIAGRAM_TYPES',
    # Simulation models (PostgreSQL)
    'Simulation',
    'SimulationResult',
    'STATUS_DRAFT', 'STATUS_READY', 'STATUS_RUNNING', 'STATUS_COMPLETED', 'STATUS_FAILED', 'STATUSES',
    'GEOMETRY_CYLINDER', 'GEOMETRY_PLATE', 'GEOMETRY_RING', 'GEOMETRY_TYPES',
    'PROCESS_TYPES', 'PROCESS_LABELS', 'DEFAULT_HTC',
]
