"""Rename provningsorder to test_order

Revision ID: 1912f9bb612f
Revises: bfdaa546e03a
Create Date: 2026-02-02 21:38:02.778190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1912f9bb612f'
down_revision = 'bfdaa546e03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_order', sa.String(length=100), nullable=True))
        batch_op.drop_column('provningsorder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provningsorder', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('test_order')

    # ### end Alembic commands ###
