"""Add certificate_id to report_approvals

Revision ID: bfdaa546e03a
Revises: 8bb8f0b33067
Create Date: 2026-02-01 15:16:23.181464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdaa546e03a'
down_revision = '8bb8f0b33067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_id', sa.Integer(), nullable=True))
        batch_op.alter_column('test_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_report_approvals_certificate_id'), ['certificate_id'], unique=True)
        batch_op.create_foreign_key('fk_report_approvals_certificate_id', 'certificates', ['certificate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_approvals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_report_approvals_certificate_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_report_approvals_certificate_id'))
        batch_op.alter_column('test_record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('certificate_id')

    # ### end Alembic commands ###
