"""Add salary tables: employees, salary_runs, salary_entries

Revision ID: 02a8ba169eaa
Revises: feb76ba101a7
Create Date: 2026-02-07 13:01:19.520177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a8ba169eaa'
down_revision = 'feb76ba101a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('personal_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('employment_start', sa.Date(), nullable=False),
    sa.Column('employment_end', sa.Date(), nullable=True),
    sa.Column('monthly_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_table', sa.String(length=10), nullable=False),
    sa.Column('tax_column', sa.Integer(), nullable=False),
    sa.Column('pension_plan', sa.String(length=10), nullable=False),
    sa.Column('bank_clearing', sa.String(length=10), nullable=True),
    sa.Column('bank_account', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_gross', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_employer_contributions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_pension', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_year', 'period_month', name='uq_company_salary_period')
    )
    op.create_table('salary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_deduction', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('employer_contributions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pension_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vacation_pay_provision', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_deductions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_additions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['salary_run_id'], ['salary_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_entries')
    op.drop_table('salary_runs')
    op.drop_table('employees')
    # ### end Alembic commands ###
