"""add fixed_assets depreciation_runs depreciation_entries tables

Revision ID: 2639c63080eb
Revises: 906c3c71db6a
Create Date: 2026-02-13 14:18:35.015795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2639c63080eb'
down_revision = '906c3c71db6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depreciation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('asset_category', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('invoice_reference', sa.String(length=100), nullable=True),
    sa.Column('depreciation_method', sa.String(length=20), nullable=True),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('residual_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('depreciation_start', sa.Date(), nullable=False),
    sa.Column('asset_account', sa.String(length=10), nullable=False),
    sa.Column('depreciation_account', sa.String(length=10), nullable=False),
    sa.Column('expense_account', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('disposed_date', sa.Date(), nullable=True),
    sa.Column('disposal_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('disposal_verification_id', sa.Integer(), nullable=True),
    sa.Column('purchase_verification_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disposal_verification_id'], ['verifications.id'], ),
    sa.ForeignKeyConstraint(['purchase_verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'asset_number', name='uq_company_asset_number')
    )
    op.create_table('depreciation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depreciation_run_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('accumulated_before', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('accumulated_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('book_value_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['fixed_assets.id'], ),
    sa.ForeignKeyConstraint(['depreciation_run_id'], ['depreciation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depreciation_entries')
    op.drop_table('fixed_assets')
    op.drop_table('depreciation_runs')
    # ### end Alembic commands ###
