"""add consolidation enhancements: intercompany_matches, acquisition_goodwill, member method

Revision ID: 29beb8d19670
Revises: 42ff8204b89e
Create Date: 2026-02-14 07:54:43.751007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29beb8d19670'
down_revision = '42ff8204b89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_goodwill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_assets_at_acquisition', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('goodwill_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amortization_period_months', sa.Integer(), nullable=True),
    sa.Column('accumulated_amortization', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['consolidation_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intercompany_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('company_a_id', sa.Integer(), nullable=False),
    sa.Column('company_b_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('match_type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('elimination_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_a_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['company_b_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['elimination_id'], ['intercompany_eliminations.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['consolidation_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consolidation_group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consolidation_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parent_member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_member_parent', 'consolidation_group_members', ['parent_member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consolidation_group_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_member_parent', type_='foreignkey')
        batch_op.drop_column('parent_member_id')
        batch_op.drop_column('consolidation_method')

    op.drop_table('intercompany_matches')
    op.drop_table('acquisition_goodwill')
    # ### end Alembic commands ###
