"""add governance tables: board_members, share_classes, shareholders, shareholder_holdings, dividend_decisions, agm_minutes

Revision ID: 54d864b89d30
Revises: 2639c63080eb
Create Date: 2026-02-13 14:36:46.066071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d864b89d30'
down_revision = '2639c63080eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('personal_number', sa.String(length=13), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('appointed_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('appointed_by', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('votes_per_share', sa.Integer(), nullable=True),
    sa.Column('par_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_share_class')
    )
    op.create_table('shareholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('personal_or_org_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shareholder_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shareholder_id', sa.Integer(), nullable=False),
    sa.Column('share_class_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=False),
    sa.Column('acquisition_type', sa.String(length=30), nullable=True),
    sa.Column('price_per_share', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['share_class_id'], ['share_classes.id'], ),
    sa.ForeignKeyConstraint(['shareholder_id'], ['shareholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividend_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_per_share', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('share_class_id', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['share_class_id'], ['share_classes.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agm_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_type', sa.String(length=30), nullable=True),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=True),
    sa.Column('chairman', sa.String(length=200), nullable=True),
    sa.Column('minutes_taker', sa.String(length=200), nullable=True),
    sa.Column('resolutions', sa.Text(), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agm_minutes')
    op.drop_table('dividend_decisions')
    op.drop_table('shareholder_holdings')
    op.drop_table('shareholders')
    op.drop_table('share_classes')
    op.drop_table('board_members')
    # ### end Alembic commands ###
