"""Add UserFavorite model

Revision ID: 6f78bd79bbb5
Revises: 1569c63a239d
Create Date: 2026-02-14 11:40:16.304578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f78bd79bbb5'
down_revision = '1569c63a239d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.create_index('ix_favorite_user_order', ['user_id', 'sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_index('ix_favorite_user_order')

    op.drop_table('user_favorites')
    # ### end Alembic commands ###
