"""Phase 4: bank, budget, consolidation, line items, document links

Revision ID: 8685c5a6667f
Revises: 02a8ba169eaa
Create Date: 2026-02-07 15:04:53.197606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8685c5a6667f'
down_revision = '02a8ba169eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('clearing_number', sa.String(length=10), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ledger_account', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'account_number', name='uq_company_bank_account')
    )
    op.create_table('consolidation_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_company_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year_id', 'account_id', 'period_month', name='uq_budget_line')
    )
    op.create_table('consolidation_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['consolidation_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'company_id', name='uq_group_company')
    )
    op.create_table('intercompany_eliminations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('from_company_id', sa.Integer(), nullable=False),
    sa.Column('to_company_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['consolidation_groups.id'], ),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('counterpart', sa.String(length=200), nullable=True),
    sa.Column('matched_verification_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('import_batch', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['matched_verification_id'], ['verifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'transaction_date', 'amount', 'description', name='uq_bank_txn')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_invoice_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_invoice_id'], ['customer_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_prefix', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pdf_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=500), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_invoice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_doc_invoice', 'supplier_invoices', ['invoice_id'], ['id'])
        batch_op.create_foreign_key('fk_doc_verification', 'verifications', ['verification_id'], ['id'])
        batch_op.create_foreign_key('fk_doc_cust_invoice', 'customer_invoices', ['customer_invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_doc_cust_invoice', type_='foreignkey')
        batch_op.drop_constraint('fk_doc_verification', type_='foreignkey')
        batch_op.drop_constraint('fk_doc_invoice', type_='foreignkey')
        batch_op.drop_column('customer_invoice_id')
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('verification_id')

    with op.batch_alter_table('customer_invoices', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')
        batch_op.drop_column('pdf_generated')
        batch_op.drop_column('invoice_prefix')

    op.drop_table('invoice_line_items')
    op.drop_table('bank_transactions')
    op.drop_table('intercompany_eliminations')
    op.drop_table('consolidation_group_members')
    op.drop_table('budget_lines')
    op.drop_table('consolidation_groups')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
