"""add annual_reports table

Revision ID: 906c3c71db6a
Revises: e6a8b3c4d5f2
Create Date: 2026-02-13 11:39:44.696657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906c3c71db6a'
down_revision = 'e6a8b3c4d5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verksamhet', sa.Text(), nullable=True),
    sa.Column('vasentliga_handelser', sa.Text(), nullable=True),
    sa.Column('handelser_efter_fy', sa.Text(), nullable=True),
    sa.Column('framtida_utveckling', sa.Text(), nullable=True),
    sa.Column('resultatdisposition', sa.Text(), nullable=True),
    sa.Column('redovisningsprinciper', sa.Text(), nullable=True),
    sa.Column('extra_noter', sa.Text(), nullable=True),
    sa.Column('board_members', sa.Text(), nullable=True),
    sa.Column('signing_location', sa.String(length=200), nullable=True),
    sa.Column('signing_date', sa.Date(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year_id', name='uq_company_fy_annual_report')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annual_reports')
    # ### end Alembic commands ###
