"""Add payment files and instructions tables

Revision ID: a6d7259597fb
Revises: 6f78bd79bbb5
Create Date: 2026-02-15 18:44:39.444981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d7259597fb'
down_revision = '6f78bd79bbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('batch_reference', sa.String(length=50), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('number_of_transactions', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_file_id', sa.Integer(), nullable=False),
    sa.Column('supplier_invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('creditor_account', sa.String(length=34), nullable=False),
    sa.Column('creditor_bic', sa.String(length=11), nullable=True),
    sa.Column('creditor_name', sa.String(length=200), nullable=False),
    sa.Column('remittance_info', sa.String(length=140), nullable=True),
    sa.Column('end_to_end_id', sa.String(length=35), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['payment_file_id'], ['payment_files.id'], ),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_file_id', 'supplier_invoice_id', name='uq_payment_file_invoice')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bic', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('bic')

    op.drop_table('payment_instructions')
    op.drop_table('payment_files')
    # ### end Alembic commands ###
