"""add tax_returns and tax_return_adjustments tables

Revision ID: acc4fc2201dd
Revises: 29beb8d19670
Create Date: 2026-02-14 08:09:58.120402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc4fc2201dd'
down_revision = '29beb8d19670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('return_type', sa.String(length=10), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('net_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_operating_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operating_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('depreciation_booked', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('financial_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('financial_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('non_deductible_expenses', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('non_taxable_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('depreciation_tax_diff', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_adjustments_add', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_adjustments_deduct', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taxable_income_before_deficit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('previous_deficit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taxable_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('calculated_tax', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_return_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_return_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sru_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tax_return_id'], ['tax_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_return_adjustments')
    op.drop_table('tax_returns')
    # ### end Alembic commands ###
