"""Add loan and direct investment fields to investment_holdings

Revision ID: b808cfac48fb
Revises: a6d7259597fb
Create Date: 2026-02-17 07:25:47.538948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b808cfac48fb'
down_revision = 'a6d7259597fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('ownership_pct', sa.Numeric(precision=7, scale=4), nullable=True))
        batch_op.add_column(sa.Column('interest_rate', sa.Numeric(precision=7, scale=4), nullable=True))
        batch_op.add_column(sa.Column('maturity_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('face_value', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('remaining_principal', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_holdings', schema=None) as batch_op:
        batch_op.drop_column('remaining_principal')
        batch_op.drop_column('face_value')
        batch_op.drop_column('maturity_date')
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('ownership_pct')
        batch_op.drop_column('org_number')

    # ### end Alembic commands ###
