"""Add address, logo, theme to Company; description, uploaded_by to Document

Revision ID: feb76ba101a7
Revises: 6c4f3e6d6a37
Create Date: 2026-02-07 09:18:28.189338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb76ba101a7'
down_revision = '6c4f3e6d6a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Companies columns - add only if not already present (idempotent for partial apply)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_company_cols = {c['name'] for c in inspector.get_columns('companies')}
    if 'street_address' not in existing_company_cols:
        with op.batch_alter_table('companies', schema=None) as batch_op:
            batch_op.add_column(sa.Column('street_address', sa.String(length=300), nullable=True))
            batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True))
            batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('logo_path', sa.String(length=500), nullable=True))
            batch_op.add_column(sa.Column('theme_color', sa.String(length=7), nullable=True))

    existing_doc_cols = {c['name'] for c in inspector.get_columns('documents')}
    if 'description' not in existing_doc_cols:
        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
            batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_uploaded_by', type_='foreignkey')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('description')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('theme_color')
        batch_op.drop_column('logo_path')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('street_address')

    # ### end Alembic commands ###
